name: Debian based machines

on:
  push:
    branches:
      - main

jobs:
  bookworm-base:
    name: Base (bookworm)
    runs-on: [self-hosted, forrest, debian-bookworm-base]
    steps:
      - name: Set up runner machine
        run: |
          sudo localectl set-locale en_US.UTF-8
          export DEBIAN_FRONTEND=noninteractive
          export DPKG_FORCE=confnew
          sudo -E apt-get update
          sudo -E apt-get --assume-yes dist-upgrade
          sudo -E apt-get --assume-yes install git rsync ssh
          sudo -E apt-get --assume-yes autoremove
          sudo -E apt-get --assume-yes clean
      - name: Persist the disk image
        env:
          PERSISTENCE_TOKEN: ${{ secrets.PERSISTENCE_TOKEN }}
        if: ${{ env.PERSISTENCE_TOKEN != ''  }}
        run: |
          sudo fstrim /
          echo "$PERSISTENCE_TOKEN" > ~/config/persist

  bookworm-yocto:
    name: Yocto (bookworm)
    needs: bookworm-base
    runs-on: [self-hosted, forrest, debian-bookworm-yocto]
    steps:
      - name: Install Software
        run: |
          sudo localectl set-locale en_US.UTF-8
          export DEBIAN_FRONTEND=noninteractive
          export DPKG_FORCE=confnew
          sudo -E apt-get update
          sudo -E apt-get --assume-yes dist-upgrade
          sudo -E apt-get --assume-yes install build-essential chrpath diffstat gawk git lz4
          sudo -E apt-get --assume-yes autoremove
          sudo -E apt-get --assume-yes clean
          sudo mkdir -p /srv/cache /srv/shared-git
          mkdir ~/.yocto
      - name: Persist the disk image
        env:
          PERSISTENCE_TOKEN: ${{ secrets.PERSISTENCE_TOKEN }}
        if: ${{ env.PERSISTENCE_TOKEN != ''  }}
        run: |
          sudo fstrim /
          echo "$PERSISTENCE_TOKEN" > ~/config/persist
