name: Debian based machines

on:
  push:
    branches:
      - main

jobs:
  bookworm-base:
    name: Base (bookworm)
    runs-on: [self-hosted, forrest, debian-bookworm-base]
    steps:
      - name: Install essential packages
        run: |
          sudo localectl set-locale en_US.UTF-8
          export DEBIAN_FRONTEND=noninteractive
          export DPKG_FORCE=confnew
          sudo -E apt-get update
          sudo -E apt-get --assume-yes dist-upgrade
          sudo -E apt-get --assume-yes install git
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: setup-data
      - name: Set up runner machine
        run: |
          export DEBIAN_FRONTEND=noninteractive
          export DPKG_FORCE=confnew
          sudo -E apt-get --assume-yes install gcc python-is-python3 rsync ssh
          $PWD/setup-data/base/setup.sh
          sudo -E apt-get --assume-yes autoremove
          sudo -E apt-get --assume-yes clean
          rm -rf setup-data
      - name: Persist the disk image
        env:
          PERSISTENCE_TOKEN: ${{ secrets.PERSISTENCE_TOKEN }}
        if: ${{ env.PERSISTENCE_TOKEN != ''  }}
        run: |
          sudo fstrim /
          echo "$PERSISTENCE_TOKEN" > ~/config/persist

  bookworm-yocto:
    name: Yocto (bookworm)
    needs: bookworm-base
    runs-on: [self-hosted, forrest, debian-bookworm-yocto]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: setup-data
      - name: Install Software
        run: |
          export DEBIAN_FRONTEND=noninteractive
          export DPKG_FORCE=confnew
          sudo -E apt-get update
          sudo -E apt-get --assume-yes dist-upgrade
          $PWD/setup-data/yocto/setup.sh
          sudo -E apt-get --assume-yes autoremove
          sudo -E apt-get --assume-yes clean
          rm -rf setup-data
      - name: Persist the disk image
        env:
          PERSISTENCE_TOKEN: ${{ secrets.PERSISTENCE_TOKEN }}
        if: ${{ env.PERSISTENCE_TOKEN != ''  }}
        run: |
          sudo fstrim /
          echo "$PERSISTENCE_TOKEN" > ~/config/persist

  bookworm-ptxdist:
    name: PTXdist (bookworm)
    needs: bookworm-base
    runs-on: [self-hosted, forrest, debian-bookworm-ptxdist]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: setup-data
      - name: Install Software
        run: |
          pwd
          ls -la
          export DEBIAN_FRONTEND=noninteractive
          export DPKG_FORCE=confnew
          sudo -E apt-get update
          sudo -E apt-get --assume-yes dist-upgrade
          $PWD/setup-data/ptxdist/setup.sh
          sudo -E apt-get --assume-yes autoremove
          sudo -E apt-get --assume-yes clean
          rm -rf setup-data
      - name: Persist the disk image
        env:
          PERSISTENCE_TOKEN: ${{ secrets.PERSISTENCE_TOKEN }}
        if: ${{ env.PERSISTENCE_TOKEN != ''  }}
        run: |
          sudo fstrim /
          echo "$PERSISTENCE_TOKEN" > ~/config/persist
